export default {
  PRODUCT_CATEGORY_GET_ALL: 'SERVER:PRODUCT_CATEGORY_GET_ALL',
  PRODUCT_CATEGORY_GET_ALL_SUCCESS: 'PRODUCT_CATEGORY_GET_ALL_SUCCESS',
  PRODUCT_CATEGORY_GET_ALL_FAILURE: 'PRODUCT_CATEGORY_GET_ALL_FAILURE',
}
