export default {
  SHOP_GET_ALL: 'SERVER:SHOP_GET_ALL',
  SHOP_GET_ALL_SUCCESS: 'SHOP_GET_ALL_SUCCESS',
  SHOP_GET_ALL_FAILURE: 'SHOP_GET_ALL_FAILURE',


  SHOP_GET_ALL_PRODUCT_CATEGORIES:         'SERVER:SHOP_GET_ALL_PRODUCT_CATEGORIES',
  SHOP_GET_ALL_PRODUCT_CATEGORIES_SUCCESS: 'SHOP_GET_ALL_PRODUCT_CATEGORIES_SUCCESS',
  SHOP_GET_ALL_PRODUCT_CATEGORIES_FAILURE: 'SHOP_GET_ALL_PRODUCT_CATEGORIES_FAILURE',


  SHOP_GET_ALL_PRODUCTS_BY_CATEGORY:         'SERVER:SHOP_GET_ALL_PRODUCTS_BY_CATEGORY',
  SHOP_GET_ALL_PRODUCTS_BY_CATEGORY_SUCCESS: 'SHOP_GET_ALL_PRODUCTS_BY_CATEGORY_SUCCESS',
  SHOP_GET_ALL_PRODUCTS_BY_CATEGORY_FAILURE: 'SHOP_GET_ALL_PRODUCTS_BY_CATEGORY_FAILURE',


  SHOP_GET_ANALITICS:         'SERVER:SHOP_GET_ANALITICS',
  SHOP_GET_ANALITICS_SUCCESS: 'SHOP_GET_ANALITICS_SUCCESS',
  SHOP_GET_ANALITICS_FAILURE: 'SHOP_GET_ANALITICS_FAILURE',
}
